
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotcast:
    sp_dc: !secret sp_dc
    sp_key: !secret sp_key

github:
  - platform: github
    access_token: !secret github_token
    repositories:
      - path: 'michda00/homeassistant'